controllers/HitosController.php
<?php

namespace app\controllers;

use app\models\Hitos;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * HitosController implements the CRUD actions for Hitos model.
 */
class HitosController extends Controller {

    public function actionNuevo() {
//            $_SESSION['submit']= false;
//        $_SESSION['proyecto']= $id;
        $_SESSION['layout'] = false;
        $_SESSION['continuar'] = true;
//        if ($_SESSION['vista'] == 'Main' || $_SESSION['vista'] == 'Nuevo' || $_SESSION['vista'] == 'Continuar') {
//            $id = Yii::$app->db->createCommand(
//                            'SELECT id FROM users
//                             WHERE username = "' . Yii::$app->user->identity->username . '"')->queryScalar();
//
//            $cuenta = Yii::$app->db->createCommand(
//                            'SELECT count(*) FROM proyectos
//                             WHERE id_user = (select id from users where username = "' . Yii::$app->user->identity->username . '")')->queryScalar();
//            'query' => Proyectos::find()->count()->where('username =' . Yii::$app->user->identity->username),
//                ]);
            $model = new Hitos();

//            if ($model->load(Yii::$app->request->post()) && Yii::$app->request->isAjax) {
//                Yii::$app->response->format = Response::FORMAT_JSON;
//                return ActiveForm::validate($model);
//            }
//    $_SESSION['submit']= 0;
            if ($this->request->isPost) {
//                if ($_SESSION['submit']=== 1){
                if ($model->load($this->request->post()) && $model->save()) {
//                    return $this->redirect(['view', 'id' => $model->id]);
                    $_SESSION['idHito'] = $model->id;
                    return $this->redirect(['objetivos/nuevo']);
                }
//                }
            } else {
                $model->loadDefaultValues();
            }

            return $this->render('nuevo', [
                        'model' => $model,
//                        'cuenta' => $cuenta + 1,
//                        'id' => $id,
            ]);
//        }
//        return $this->redirect(["site/index"]);
    }

    public function actionEditar($id) {
        $model = $this->findModel($id);
        $_SESSION['layout'] = true;
        $_SESSION['idHito'] = $id;
        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['proyectos/continuar', 'id' => $_SESSION['idProyecto'], 'hito' => $_SESSION['idHito']]);
        }

        return $this->render('editar', [
                    'model' => $model,
        ]);
    }

    /**
     * @inheritDoc
     */
    public function behaviors() {
        return array_merge(
                parent::behaviors(),
                [
                    'verbs' => [
                        'class' => VerbFilter::className(),
                        'actions' => [
                            'delete' => ['POST'],
                        ],
                    ],
                ]
        );
    }

    /**
     * Lists all Hitos models.
     *
     * @return string
     */
    public function actionIndex() {
        $dataProvider = new ActiveDataProvider([
            'query' => Hitos::find(),
                /*
                  'pagination' => [
                  'pageSize' => 50
                  ],
                  'sort' => [
                  'defaultOrder' => [
                  'id' => SORT_DESC,
                  ]
                  ],
                 */
        ]);

        return $this->render('index', [
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Hitos model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id) {
        return $this->render('view', [
                    'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Hitos model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate() {
        $model = new Hitos();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
                    'model' => $model,
        ]);
    }

    /**
     * Updates an existing Hitos model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id) {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
                    'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Hitos model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id) {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Hitos model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Hitos the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Hitos::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\Logros;
use app\models\ContactForm;
use app\models\ValidarFormulario;
use app\models\ValidarFormularioAjax;
use yii\widgets\ActiveForm;
use app\models\FormRegister;
use app\models\Users;
use yii\web\Session;
use app\models\FormRecoverPass;
use app\models\FormResetPass;
use yii\helpers\Url;
use yii\helpers\Html;
use app\controllers\ProyectosController;

// ejemplo de pruebas del proyecto: "C:\xampp\htdocs\dam\proyectos\gestionproyectos"
// direccion de la carpeta del proyecto posterior al htdocs: --> 'dam\proyectos\gestionproyectos' <--
//substr(Yii::$app->homeUrl, 1,-14) = substr(Yii::$app->homeUrl, 1,-14); //obtener automaticamente la direccion
$homeUrl = Yii::$app->homeUrl;
$_SESSION['dir'] = substr($homeUrl, 1, -14);

if (!isset($_SESSION['proyecto'])) {
    $_SESSION['proyecto'] = "null";
}
if (!isset($_SESSION['plazo'])) {
    $_SESSION['plazo'] = "null";
}
if (!isset($_SESSION['tiempo'])) {
    $_SESSION['tiempo'] = "null";
}
if (!isset($_SESSION['totalHitos'])) {
    $_SESSION['totalHitos'] = "null";
}
if (!isset($_SESSION['totalObjetivos'])) {
    $_SESSION['totalObjetivos'] = "null";
}
if (!isset($_SESSION['totalTareas'])) {
    $_SESSION['totalTareas'] = "null";
}
if (!isset($_SESSION['tipo'])) {
    $_SESSION['tipo'] = "null";
}
if (!isset($_SESSION['idObjetivo'])) {
    $_SESSION['idObjetivo'] = "null";
}
if (!isset($_SESSION['idHito'])) {
    $_SESSION['idHito'] = "null";
}
if (!isset($_SESSION['pagProyecto'])) {
    $_SESSION['pagProyecto'] = 0;
}

class SiteController extends Controller {

    /**
     * {@inheritdoc}
     */
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex() {

//        $_SESSION['dir'] = substr(Yii::$app->homeUrl, 1, -14); //obtener automaticamente la direccion

        $_SESSION['continuar'] = false;
        $_SESSION['layout'] = false;
        $_SESSION['idProyecto'] = null;
        return $this->render('index');
    }

    public function actionComenzar() {
//        if ($_SESSION['vista'] == 'Main' || $_SESSION['vista'] == 'Comenzar') { //con el 'or' no devolvemos al usuario al main al recargar la pagina
        return $this->redirect(['proyectos/nuevo']);
//        }
//        return $this->render('index');
    }

    public function actionContinuar() {
//            if ($_SESSION['vista'] == 'Main' || $_SESSION['vista'] == 'Nuevo') {
        if (isset($_SESSION['idProyecto'])) {
            return $this->redirect(['proyectos/continuar', 'id' => $_SESSION['idProyecto'], /* 'hitos'=> "null", */ 'hito' => $_SESSION['idHito']]);
        } else {
        return $this->redirect(['proyectos/seleccionar']);
        }
//    }
//        return $this->render('index');
    }

    public function actionLogros() {
        $model = UsersController::findThis(Yii::$app->user->getId());

        $proyectos = $model->proyectos;

        $horas = 0;
        $minutos = 0;
        $segundos = 0;
        $totalHitos = 0;
        $hitosCompletados = 0;
        $objetivosCompletados = 0;
        $totalObjetivos = 0;
        $tareasCompletadas = 0;
        $totalTareas = 0;

        foreach ($proyectos as $proyecto) {
            $horas += ProyectosController::updateLayout($proyecto->id, 'horas');
            $minutos += ProyectosController::updateLayout($proyecto->id, 'minutos');
            $segundos += ProyectosController::updateLayout($proyecto->id, 'segundos');
            $hitosCompletados += ProyectosController::updateLayout($proyecto->id, 'hitosCompletados');
            $totalHitos += ProyectosController::updateLayout($proyecto->id, 'totalHitos');
            $objetivosCompletados += ProyectosController::updateLayout($proyecto->id, 'objetivosCompletados');
            $totalObjetivos += ProyectosController::updateLayout($proyecto->id, 'totalObjetivos');
            $tareasCompletadas += ProyectosController::updateLayout($proyecto->id, 'tareasCompletadas');
            $totalTareas += ProyectosController::updateLayout($proyecto->id, 'totalTareas');
        }

        $minutos += (int) ($segundos / 60);

        $horas += (int) ($minutos / 60);
        if ($horas < 10) {
            $horas = '0' . $horas;
        }

        $minutos -= 60 * (int) ($minutos / 60);
        if ($minutos < 10) {
            $minutos = '0' . $minutos;
        }

        $segundos -= 60 * (int) ($segundos / 60);
        if ($segundos < 10) {
            $segundos = '0' . $segundos;
        }

        $tiempo = 'Total: ' . $horas . ':' . $minutos/* . ' segundos: '.$segundos */;

        return $this->render('logros', [
                    'horas' => $horas,
                    'minutos' => $minutos,
                    'segundos' => $segundos,
                    'tiempo' => $tiempo,
                    'tiempo' => $tiempo,
                    'totalHitos' => $totalHitos,
                    'hitosCompletados' => $hitosCompletados,
                    'objetivosCompletados' => $objetivosCompletados,
                    'totalObjetivos' => $totalObjetivos,
                    'tareasCompletadas' => $tareasCompletadas,
                    'totalTareas' => $totalTareas,
                    'nProyectos' => count($proyectos),
        ]);
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin() {
//        if (!isset($_SESSION['presentacion'])) {
//            $_SESSION['presentacion'] = '';
//            $_SESSION['iniciar'] = 'd-none';
//        } else {
        $_SESSION['presentacion'] = 'd-none';
        $_SESSION['iniciar'] = '';
//        }
        $_SESSION['layout'] = 0;
        $_SESSION['dir'] = substr(Yii::$app->homeUrl, 1, -14); //obtener automaticamente la direccion

        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->contraseña = '';
        return $this->render('login', [
                    'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout() {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionSalir() {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact() {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
                    'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionCrud() {
        $_SESSION['presentacion'] = 'd-none';
        $_SESSION['iniciar'] = '';
        return $this->redirect(['site/login']);
    }

    // tut 1




    public function actionFormulario($mensaje = null) {
        return $this->render("formulario", ["mensaje" => $mensaje]);
    }

    public function actionRequest() {
        $mensaje = null;
        if (isset($_REQUEST["nombre"])) {
            $mensaje = "Bien, has enviando tu nombre correctamente: " . $_REQUEST["nombre"];
        }
        $this->redirect(["site/formulario", "mensaje" => $mensaje]);
    }

    public function actionValidarformulario() {

        $model = new ValidarFormulario;
        $msg = null;

        if ($model->load(Yii::$app->request->post())) {
            if ($model->validate()) {
                //Por ejemplo, consultar en una base de datos
                $msg = "funciona";
                $model->nombre = null;
                $model->email = null;
            } else {
                $model->getErrors();
            }
        }

        return $this->render("validarformulario", ["model" => $model, 'msg' => $msg]);
    }

    public function actionValidarformularioajax() {
        $model = new ValidarFormularioAjax;
        $msg = null;

        if ($model->load(Yii::$app->request->post()) && Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }

        if ($model->load(Yii::$app->request->post())) {
            if ($model->validate()) {
                //Por ejemplo hacer una consulta a una base de datos
                $msg = "Enhorabuena formulario enviado correctamente";
                $model->nombre = null;
                $model->email = null;
            } else {
                $model->getErrors();
            }
        }

views/site/comenzar.php
<?php

use yii\bootstrap4\Html;

$this->title = 'Comenzar';
?>

<!--<div class="h-100 row text-center">
    <div class="mt-5 pt-5 col align-self-lg-start">
        <div class="mt-5 pt-5 row justify-content-center">

            <div class="col-md-3 col-sm-3">
            </div>

            <div class="col-md-6 col-sm-6 text-center">

                <div class="">

                    <p class="shine text-white display-4">¿Tiene nombre tu proyecto?</p>

                </div>

                <div class="mt-5 row justify-content-center">

                    <div class="my-5 bgb col-md-4 col-sm-4 text-center">
                        < ?= Html::a('Si', ['proyectos/nuevo'], ['class' => 'btn btn-zelda']) ?>
                    </div>

                    <div class="col-md-1 col-sm-1">
                    </div>

                    <div class="my-5 bgb col-md-4 col-sm-4 text-center">
                        < ?= Html::a('No', ['proyectos/plazo'], ['class' => 'btn btn-zelda']) ?>
                    </div>

                </div>

            </div>

            <div class="col-md-3 col-sm-3">
            </div>

        </div>
    </div>
</div>-->

views/site/contact.php
<?php

/** @var yii\web\View $this */
/** @var yii\bootstrap4\ActiveForm $form */
/** @var app\models\ContactForm $model */

use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Html;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="bgb container-fluid flex-fill">asd </div>



<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/continuar.php
<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
$this->title = 'Continuar';

views/site/crud.php
<?php

/** @var yii\web\View $this */
use yii\bootstrap4\Html;

$this->title = 'CRUD';
//$this->params['breadcrumbs'][] = $this->title;
$_SESSION['layout'] = true;
?>
<div id="pruebas del layout">

<!--    <div class="navbar-bg">
        <div class="col align-self-lg-center navbar">

            <div class="w-100 row justify-content-center">-->


                <!--                <div class="col-md-4 col-sm-4 col align-self-lg-center" style="background-color: red">
                
                                    <div class="col-md-12 col-sm-12" style="background-color: violet">
                                        <h2 class="text-center"> <?= Html::a($_SESSION['proyecto'], ['proyectos/continuar', 'id' => $_SESSION['idProyecto'], 'hito' => $_SESSION['idHito']], ['class' => 'a text-white']) ?> </h2>
                                    </div>
                
                                    <div class="col-md-12 col-sm-12" style="background-color: violet">
                                        <h2 class="text-white text-center"><?= '<i class="fas fa-calendar-alt"></i> ' . $_SESSION['plazo'] . ' <i class="fas fa-clock"></i> ' . $_SESSION['tiempo'] ?></h2>
                                    </div>
                
                                    <div class="col-md-12 col-sm-12" style="background-color: violet">
                                        <h2 class="text-white text-center"><?= '<i class="fas fa-flag"></i> ' . $_SESSION['totalHitos'] . ' <i class="fas fa-bullseye"></i> ' . $_SESSION['totalObjetivos'] . ' <i class="fas fa-clipboard"></i> ' . $_SESSION['totalTareas'] ?></h2>
                                    </div>
                
                                </div>-->




                <!--MAPA-->
                <!--                <div id="mapa" class="col-md-5 d-flex col-sm-5 col align-self-lg-center text-center p-2 map">
                                    style="background-color: yellow">
                                    <div id="zona-1" class="col align-self-lg-center text-center">
                                         style="background-color: blue">
                                        <h1 class="fas fa-map">  </h1>
                                    </div>
                
                                    <div id="zona-2" class="col align-self-lg-center text-center">
                                        style="background-color: blue">
                                        <h1 class="fas fa-map"> </h1>
                                    </div>
                
                                    <div id="zona-3" class="col align-self-lg-center text-center">
                                        style="background-color: blue">
                                        <h1 class="fas fa-map"> </h1>
                                    </div>
                
                                    <div id="zona-4" class="col align-self-lg-center text-center">
                                        style="background-color: blue">
                                        <h1 class="fas fa-map"> </h1>
                                    </div>
                
                                    <div id="zona-5" class="col align-self-lg-center text-center">
                                        style="background-color: blue">
                                        <h1 class="fas fa-map"> </h1>
                                    </div>
                                </div>-->
                <!--MAPA fin-->




                <!--                <div class="col-md-3 col-sm-3 col align-self-lg-center" style="background-color: green">
                
                                    <div class="h-50 col-md-12 col-sm-12" style="background-color: violet">
                                        <h1>NOTIFICACIONES <i class="fas fa-bell"></i></h1>
                                    </div>
                
                                    <div class="h-50 col-md-12 col-sm-12" style="background-color: violet">
                                        <h1>RECORDATORIOS <i class="fas fa-calendar-plus"></i></h1>
                                    </div>
                
                                </div>-->


<!--            </div>

        </div>
    </div>-->

</div>




<!--        <main role="main" class="d-flex flex-grow-0">
            <div class="container-fluid">

                <div class="d-flex bd-highlight">
  <div class="p-2 flex-grow-1 bd-highlight">Flex item</div>
  <div class="p-2 bd-highlight">Flex item</div>
  <div class="p-2 bd-highlight">Third flex item</div>
</div>
                
            </div>
        </main>-->

<!--                <div class="d-flex bd-highlight bgb w-100">
  <div class="p-2 flex-grow-1 bd-highlight">Flex item</div>
  <div class="p-2 bd-highlight">Flex item</div>
  <div class="p-2 bd-highlight">Third flex item</div>
</div>-->



<!--<button type="button" class="q badge  rounded-circle" data-toggle="tooltip" data-placement="top" title="Hooray!">?</button>
<div class="h-100 row text-center">
    <div class="col align-self-center">
        <div class="row justify-content-center">
            <div class="col-4">
            </div>
            <div class="col-4">
            </div>
            <div class="col-3 bgb">
                One of two columns
            </div>
        </div>
    </div>
</div>-->

<!--<div class="bgb col-12 flex#{$infix}-grow-1 w-100">asd</div>-->
<!--<div>
    <h1  Html::encode($this->title) ?></h1>

    <p>
        < ?= Html::a('Usuarios', ['users/index'], ['class' => 'btn btn-warning']) ?>
        < ?= Html::a('Proyectos', ['proyectos/index'], ['class' => 'btn btn-warning']) ?>
        < ?= Html::a('Hitos', ['hitos/index'], ['class' => 'btn btn-warning']) ?>
        < ?= Html::a('Objetivos', ['objetivos/index'], ['class' => 'btn btn-warning']) ?>
        < ?= Html::a('Tareas', ['tareas/index'], ['class' => 'btn btn-warning']) ?>
        < ?= Html::a('Instrucciones', ['instrucciones/index'], ['class' => 'btn btn-warning']) ?>
        < ?= Html::a('Sesiones', ['sesiones/index'], ['class' => 'btn btn-warning']) ?>
        < ?= Html::a('Recordatorios', ['recordatorios/index'], ['class' => 'btn btn-warning']) ?>
        < ?= Html::a('ObjetivosEnHitos', ['objetivos-en-hitos/index'], ['class' => 'btn btn-warning']) ?>
        < ?= Html::a('ProductosAObtener', ['productos-a-obtener/index'], ['class' => 'btn btn-warning']) ?>
        
    </p>

    <code>< ?= __FILE__ ?></code>
</div>-->

views/site/error.php
<?php

/** @var yii\web\View $this */
/** @var string $name */
/** @var string $message */
/** @var Exception$exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

use yii\bootstrap4\Html;

$this->title = 'Main';
?>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        particulasIndex();
    });
</script>

<div class="h-100 row text-center">
    <div class="col align-self-end">
        <div class="row justify-content-center">

            <div class="col-md-8 col-sm-8">
                <div class="p-5">  
                </div>
            </div>

            <div class="mb-4 pb-4 col-md-3 col-sm-3 text-right user-select-none">

                <a href=""><div class="logo mb-5 mr-4"></div></a>

                <div class="py-5">

                    <div class="m-5 pr-5 py-1">
                        <a onmouseover="hoverSound('<?= $_SESSION['dir'] ?>', 'HoverSmall')" 
                           onclick="clickSound('<?= $_SESSION['dir'] ?>', 'null', 'comenzar', 6541), startGame('<?= $_SESSION['dir'] ?>')" 
                           class="a text-white display-4">
                            Comenzar
                        </a>
                        <?= Html::a('', ['site/comenzar'], ['id' => 'comenzar']) ?>
                    </div>

                    <div class="m-5 pr-5 py-1">
                        <a onmouseover="hoverSound('<?= $_SESSION['dir'] ?>', 'HoverSmall')" 
                           onclick="clickSound('<?= $_SESSION['dir'] ?>', 'HoverBig_Click', 'continuar', 1500)" 
                           class="a text-white display-4">
                            Continuar
                        </a>
                        <?= Html::a('', ['site/continuar'], ['id' => 'continuar']) ?>
                    </div>

                    <div class="m-5 pr-5 py-1">
                        <a onmouseover="hoverSound('<?= $_SESSION['dir'] ?>', 'HoverSmall')" 
                           onclick="clickSound('<?= $_SESSION['dir'] ?>', 'Extra_Click', 'logros', 300)" 
                           class="a text-white display-4">
                            Logros
                        </a>
                        <?= Html::a('', ['site/logros'], ['id' => 'logros']) ?>
                    </div>

                    <div class="m-5 pr-5 py-1">
                        <a onmouseover="hoverSound('<?= $_SESSION['dir'] ?>', 'HoverSmall')" 
                           onclick="clickSound('<?= $_SESSION['dir'] ?>', 'Back', 'salir', 300)" 
                           class="a text-white display-4">
                            Salir
                        </a>
                        <?= Html::a('', ['site/salir'], ['id' => 'salir']) ?>
                    </div>

                </div>

            </div>

        </div>
    </div>
</div>

views/site/validarformulario.php
<?php

use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Html;


?>
<h3><?= $msg ?></h3>
<h1>Validar Formulario</h1>
<?php $form = ActiveForm::begin([
    "method" => "post",
 'enableClientValidation' => true,
]);
?>
<div class="form-group">
 <?= $form->field($model, "nombre")->input("text") ?>   
</div>

<div class="form-group">
 <?= $form->field($model, "email")->input("email") ?>   
</div>

<?= Html::submitButton("Enviar", ["class" => "btn btn-primary"]) ?>

<?php $form->end() ?>

views/site/validarformularioajax.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>

<h3><?= $msg ?></h3>

<h1>validar formulario ajax</h1>
<?php
$form = ActiveForm::begin([
            'method' => 'post',
            'id' => 'formulario',
            'enableClientValidation' => false,
            'enableAjaxValidation' => true,
        ]);
?>
<div class="form-group">
<?= $form->field($model, "nombre")->input("text") ?>   
</div>

<div class="form-group">
<?= $form->field($model, "email")->input("email") ?>   
</div>

<!--<div class="form-group">
< ?= $form->field($model, "password")->input("password") ?>   
</div>

<div class="form-group">
< ?= $form->field($model, "password_repeat")->input("password") ?>   
</div>-->

<?= Html::submitButton("Register", ["class" => "btn btn-primary"]) ?>

<?php $form->end() ?>