models/Tareas.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "tareas".
 *
 * @property int $id
 * @property string $nombre
 * @property string|null $descripcion
 * @property int $completada
 * @property int $id_objetivo
 *
 * @property Instrucciones[] $instrucciones
 * @property Objetivos $objetivo
 * @property Recordatorios[] $recordatorios
 * @property Sesiones[] $sesiones
 */
class Tareas extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'tareas';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['nombre', 'completada', 'id_objetivo'], 'required'],
            [['completada', 'id_objetivo'], 'integer'],
            [['nombre'], 'string', 'max' => 20],
            [['descripcion'], 'string', 'max' => 300],
            [['id_objetivo'], 'exist', 'skipOnError' => true, 'targetClass' => Objetivos::className(), 'targetAttribute' => ['id_objetivo' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nombre' => 'Nombre',
            'descripcion' => 'Descripcion',
            'completada' => 'Completada',
            'id_objetivo' => 'Id Objetivo',
        ];
    }

    /**
     * Gets query for [[Instrucciones]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getInstrucciones()
    {
        return $this->hasMany(Instrucciones::className(), ['id_tarea' => 'id']);
    }

    /**
     * Gets query for [[Objetivo]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getObjetivo()
    {
        return $this->hasOne(Objetivos::className(), ['id' => 'id_objetivo']);
    }

    /**
     * Gets query for [[Recordatorios]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getRecordatorios()
    {
        return $this->hasMany(Recordatorios::className(), ['id_tarea' => 'id']);
    }

    /**
     * Gets query for [[Sesiones]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getSesiones()
    {
        return $this->hasMany(Sesiones::className(), ['id_tarea' => 'id']);
    }
}

controllers/TareasController.php
<?php

namespace app\controllers;

//use app\controllers\ProyectosController;
use app\models\Tareas;
use app\models\Proyectos;
use app\models\Sesiones;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;
use Yii;

/**
 * TareasController implements the CRUD actions for Tareas model.
 */
class TareasController extends Controller {

    public function actionNuevo() {
        $_SESSION['layout'] = false;

//        if ($_SESSION['vista'] == 'Main' || $_SESSION['vista'] == 'Nuevo' || $_SESSION['vista'] == 'Continuar') {

            $model = new Tareas();

            if ($this->request->isPost) {

                if ($model->load($this->request->post()) && $model->save()) {
                    $_SESSION['idTarea'] = $model->id;
                    return $this->redirect(['instrucciones/nuevo']);
                }
            } else {
                $model->loadDefaultValues();
            }

            return $this->render('nuevo', [
                        'model' => $model,
            ]);
//        }
//        return $this->redirect(["site/index"]);
    }

    public function actionContinuar($id) {
        ProyectosController::updateLayout($_SESSION['idProyecto'],'update');
        unset($_SESSION['idSesion']);
        unset($_SESSION['inicioSesion']);
        unset($_SESSION['finSesion']);
        $model = $this->findModel($id);
        $_SESSION['layout'] = true;
        $_SESSION['continuar'] = true;
        $_SESSION['idTarea'] = $model->id;
        $map = ArrayHelper::map($model->sesiones, 'hora_inicio', 'hora_fin', 'id');
        foreach ($map as $i => $hInicio) {
            $_SESSION['idSesion'] = $i;
            foreach ($map[$i] as $x => $y) {
                $_SESSION['inicioSesion'] = $x;
                $_SESSION['finSesion'] = $y;
            }

//            $_SESSION['debug'] = $map;
//            $_SESSION['idSesion'] = ArrayHelper::getColumn($sesion, 'id');
//            $_SESSION['inicioSesion'] = ArrayHelper::getColumn($sesion, 'hora_inicio');
//                                                        $_SESSION['inicioSesion'] = strval(array_column($model->sesiones, 'hora_inicio'));
//                                                        $_SESSION['finSesion'] = print_r($model->sesiones);
//                                                $_SESSION['idSesion'] = $model->id;$duracion = preg_split("/:/", $time);
//                                                $horas += intval($duracion[0]);
//                                                $minutos += intval($duracion[1]);
//                                                $segundos += intval($duracion[2]);
        }
        $ls = new ActiveDataProvider([
//            'query' => Objetivos::find()->where(['in', 'id', array_values(ArrayHelper::map($objetivos, 'id_objetivo', 'id_objetivo'))]),
            'query' => Sesiones::find()->where("id = (select max(id) from sesiones) && id_tarea=" . $_SESSION['idTarea'])->one()
        ]);
        $_SESSION['debug'] = $ls;
//        $_SESSION['idSesion'] = $model->id;
//        
//        $_SESSION['proyecto'] = $model->titulo_proyecto;
//        $_SESSION['layout'] = true;
//        $_SESSION['continuar'] = true;
//        $_SESSION['idHito'] = $hito;
//        $_SESSION['plazo'] = $model->plazo_entrega;
//        $_SESSION['tipo'] = $model->tipo;
//        switch ($_SESSION['tipo']) {
//            case 'Personal':
//                $_SESSION['tipo'] = '<i class="fa-solid fa-mug-hot"></i> ';
//                break;
//            case 'Estudios':
//                $_SESSION['tipo'] = '<i class="fa-solid fa-graduation-cap"></i> ';
//                break;
//            case 'Investigación':
//                $_SESSION['tipo'] = '<i class="fa-solid fa-microscope"></i> ';
//                break;
//            default:
//                $_SESSION['tipo'] = '<i class="fa-solid fa-seedling"></i> ';
//        }
//        if (strlen($_SESSION['plazo']) === 0) {
//            $_SESSION['plazo'] = 'Sin plazo de entrega';
//        }
//        if (isset($_SESSION['idProyecto']) || isset($id)) {
//            if (isset($id)) {
//                $_SESSION['idProyecto'] = $id;
//            }
//            $hitos = ArrayHelper::map($model->hitos, 'id', 'nombre_descriptivo');
//            $objetivos = Yii::$app->db->createCommand(
//                            'SELECT DISTINCT id_objetivo FROM objetivos_en_hitos
//                             WHERE id_hito ='
//                            . $hito)->queryAll();
        $dataProvider = new ActiveDataProvider([
//            'query' => Objetivos::find()->where(['in', 'id', array_values(ArrayHelper::map($objetivos, 'id_objetivo', 'id_objetivo'))]),
            'query' => Tareas::find()->where("id =" . $id)
        ]);
        return $this->render('continuar', [
                    'dp' => $dataProvider,
                    'titulo' => $model->nombre,
                    'ls' => $ls,
//                        'id' => $hito,
//                        'hitos' => $hitos,
//                        'proyecto' => $model->titulo_proyecto,
        ]);
//        } else {
//            $this->redirect(['site/index']);
//        }
    }

    public function actionEditar($id) {
        $model = $this->findModel($id);
        $_SESSION['layout'] = true;

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['tareas/continuar', 'id' => $_SESSION['idTarea']]);
        }

        return $this->render('editar', [
                    'model' => $model,
        ]);
    }

    public function actionCompletada($id) {
        $model = $this->findModel($id);
        $_SESSION['layout'] = true;

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['tareas/continuar', 'id' => $_SESSION['idTarea']]);
        }

        return $this->render('completada', [
                    'model' => $model,
        ]);
    }

    /**
     * @inheritDoc
     */
    public function behaviors() {
        return array_merge(
                parent::behaviors(),
                [
                    'verbs' => [
                        'class' => VerbFilter::className(),
                        'actions' => [
                            'delete' => ['POST'],
                        ],
                    ],
                ]
        );
    }

    /**
     * Lists all Tareas models.
     *
     * @return string
     */
    public function actionIndex() {
        $dataProvider = new ActiveDataProvider([
            'query' => Tareas::find(),
                /*
                  'pagination' => [
                  'pageSize' => 50
                  ],
                  'sort' => [
                  'defaultOrder' => [
                  'id' => SORT_DESC,
                  ]
                  ],
                 */
        ]);

        return $this->render('index', [
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Tareas model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id) {
        return $this->render('view', [
                    'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Tareas model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate() {
        $model = new Tareas();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
                    'model' => $model,
        ]);
    }

    /**
     * Updates an existing Tareas model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id) {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
                    'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Tareas model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id) {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Tareas model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Tareas the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Tareas::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

}

views/tareas/_completada.php
<?php

use yii\bootstrap4\Html;
use yii\bootstrap4\ActiveForm;
use yii\widgets\LinkPager;

/* @var $this yii\web\View */
/* @var $model app\models\Tareas */
/* @var $form yii\widgets\ActiveForm */
?>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        completada();
    });
</script>

<div class="tareas-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'nombre')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'descripcion')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'completada')->textInput(['id' => 'completada']) ?>

    <?= $form->field($model, 'id_objetivo')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success', 'id' => 'submit-button']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/tareas/_continuar.php
<?php

use yii\bootstrap4\Html;
use yii\helpers\ArrayHelper;

$this->title = 'Continuar';
$estado = '';
$mostrar = '';
$mostrarTiempo = '';

if (!isset($_SESSION['idSesion'])) {
    $_SESSION['idSesion'] = '';
}

if ($model->completada === 0) {
    $completada = 'completada';
    $mostrar = '';
    $mostrarTiempo = 'd-none ';
} else {
    $completada = 'incompleta';
    $estado = 'fa-solid fa-check';
    $mostrar = 'd-none ';
    $mostrarTiempo = '';
}
$contador = 'patata';
$trabajar = '';
$parar = 'd-none ';
$trabajando = 0;

if (isset($_SESSION['finSesion'])) {
    $contador = '00:00:00';
} else {
    if (isset($_SESSION['inicioSesion'])) {
        $contador = substr($_SESSION['inicioSesion'], 11, 8);
        $trabajando = 1;
        $trabajar = 'd-none ';
        $parar = '';
    }
}
?>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        init(<?= $trabajando ?>, '<?= $contador ?>');
        fin(<?= $trabajando ?>, '<?= $estado ?>');
        ajustarVolumen(13);
    });
</script>

<div class="bgb my-3 w-100">        
    <div class="borde p-2">

        <div class="col align-self-lg-center">
            <div class="row justify-content-center">

                <!--TITULO Y DESCRIPCION-->
                <div class="col-md-8 col-sm-8">
                    <h1 class="text-left display-4"><?= $model->nombre ?> <span><i class="<?= $estado ?>"></i></span> <span class="navbar"></span></h1>
                    <p class="text-justify"> <?= $model->descripcion ?></p>
                </div>

                <!--arriba derecha-->
                <div class="col-md-4 col-sm-4">
                    <div class="bgb-40 <?= $parar ?>">        
                        <div class="borde">
                            <div class="text-center">
                                <iframe id="player" class="py-5 mt-1 mb-n1" src="https://www.youtube.com/embed/sWtEYPva4A0?modestbranding=1&;showinfo=0&enablejsapi=1&autoplay=<?= $trabajando ?>" frameborder="0" allow="autoplay"></iframe>
                            </div>
                        </div>
                    </div>
                </div>

                <!--INSTRUCCIONES-->
                <div class="mt-4 col-md-8  col-sm-8">
                    <div class="bgb">
                        <div class="borde">
                            <h4 class="pl-2 pt-1"> Instrucciones</h4>
                            <div class="instrucciones w-100 asdh-25 mt-3 mb-0 ml-0 bgb row example-1 square scrollbar-dusty-grass thin bordered-z">
                                <div class="col align-self-lg-start">
                                    <div class="row justify-content-start">
                                        <div class="asd">
                                            <div class="">
                                                <!--CONTENIDO EDITABLE-->
                                                <div class="pl-3">
                                                    <?php
                                                    foreach (ArrayHelper::map($model->instrucciones, 'id', 'paso') as $id => $paso) {

//                                                        echo Html::a('<p class="text-justify mr-3">-' . $paso . ' <i class="fa-solid fa-paintbrush"></i></p>', ['instrucciones/editar', 'id' => $id], ['class' => 'a text-white']);

                                                        echo '<a onmouseover="hoverSound(\'' . $_SESSION['dir'] . '\', \'HoverSmall\')" ' .
                                                        'onclick = "clickSound(\'' . $_SESSION['dir'] . '\', \'Mod_Open\', \'instrubtn\', 419)" ' .
                                                        'class = "a text-white"> ' .
                                                        '<p class="text-justify mr-3">-' . $paso . ' <i class="fa-solid fa-paintbrush"></i></p>' .
                                                        '</a>' .
                                                        Html::a('', ['instrucciones/editar', 'id' => $id], ['class' => 'd-none', 'id' => 'instrubtn']);
                                                    }
                                                    ?>
                                                </div>
                                                <div class="pl-3 pb-2">

                                            <!--< ?= Html::a('<i class="fas fa-plus"></i> Añadir instrucción', ['instrucciones/nuevo'], ['class' => 'a px-5 py-2 badge badge-zelda']) ?>-->
                                                    <a onmouseover="hoverSound('<?= $_SESSION['dir'] ?>', 'HoverSmall')" 
                                                       onclick="clickSound('<?= $_SESSION['dir'] ?>', 'Talk_Next', 'nbtn', 419)" 
                                                       class="a px-5 py-2 badge badge-zelda">
                                                        <i class="fas fa-plus"></i> Añadir instrucción
                                                    </a>
                                                    <?= Html::a('', ['instrucciones/nuevo'], ['class' => 'd-none', 'id' => 'nbtn']) ?>
                                                </div>
                                                <div class="pl-3">

                                                    <!--                                                    < ?php
                                                    //                                                    echo print_r(pos($ls));
                                                    //                                                    echo '<p>debug: </p>';
                                                    //                                                    echo isset($_SESSION['finSesion']);
                                                    //                                                    echo print_r(pos($_SESSION['debug']));
                                                    //                                                    echo '<p>inicio: </p>';
                                                    //                                                    echo pos($ls)['hora_inicio'];
                                                    //                                                    echo $_SESSION['inicioSesion'];
                                                    //                                                    if (isset($_SESSION['inicioSesion'])) {
                                                    //                                                        echo $_SESSION['inicioSesion'];
                                                    //                                                    }
                                                    //                                                    echo '<p>id: <p>';
                                                    
                                                    //                                                    if (isset($_SESSION['idSesion'])) {
                                                    //                                                        echo $_SESSION['idSesion'];
                                                    //                                                    }
                                                    
                                                    //                                                    echo $_SESSION['idSesion'];
                                                    //                                                    echo pos($ls)['id'];
                                                    //                                                    echo print_r($_SESSION['inicioSesion']);
                                                    //                                                    echo '<p>fin: <p>';
                                                    //                                                    echo pos($ls)['hora_fin'];
                                                    //                                                    echo print_r($_SESSION['debug']);
                                                    //                                                    $_SESSION['finSesion']
                                                    //                                                    if (isset($_SESSION['finSesion'])) {
                                                    //                                                        echo $_SESSION['finSesion'];
                                                    //                                                    }
                                                    //                                                    $_SESSION['idSesion'].'<p>';
                                                    //                                                    foreach (ArrayHelper::map($model->sesiones, 'id', 'hora_inicio') as $id => $paso) {
                                                    //                                                        echo Html::a('<p class="text-justify mr-3">-' . $paso . ' <i class="fa-solid fa-paintbrush"></i></p>', ['instrucciones/editar', 'id' => $id], ['class' => 'a text-white']);
                                                    //                                                    }
                                                                                                        ?>-->
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="py-3">
                        <div class="row justify-content-center">
                            <div class="col-md-6 col-sm-6">    
                                <!--< ?= Html::a('', ['tareas/completada', 'id' => $model->id], ['class' => 'bgb btn btn-zelda']) ?>-->
                                <a onmouseover="hoverSound('<?= $_SESSION['dir'] ?>', 'HoverSmall')" 
                                   onclick="clickSound('<?= $_SESSION['dir'] ?>', 'BlueFire_BurnStart', 'marcar', 1000)" 
                                   class="bgb btn btn-zelda">
                                    Marcar tarea como <span class="font-weight-bolder"><?= $completada ?></span>
                                </a>
                                <?= Html::a('', ['tareas/completada', 'id' => $model->id], ['class' => 'd-none', 'id' => 'marcar']) ?>
                            </div>
                        </div>
                    </div>
                </div>


                <!--derecha abajo-->
                <div class="col-md-4 col-sm-4 col align-self-center mb-5 pb-4">
                    <div class="bgb-40 my-3 w-100">        
                        <div class="borde p-5">
                            <div class="<?= $mostrarTiempo ?>text-center">
                                <?php
                                if (isset($_SESSION['tiempo-' . $_SESSION['idTarea']])) {
                                    echo $_SESSION['tiempo-' . $_SESSION['idTarea']];
                                } else {
                                    echo '<p class="shine h4">Sin registros de tiempo</p>';
                                }
                                ?>
                            </div>
                            <div class="<?= $mostrar ?>">

                                <div class="text-center shine pb-5">
                                    <div id="hms"></div>
                                    <div class="d-none start"></div>        
                                    <div class="d-none stop"></div>
                                    <div class="d-none reiniciar"></div>
                                </div>

                            </div>

                            <div class="<?= $mostrar ?>text-right">    
                                <!--BOTONES-->

                                <a onmouseover="hoverSound('<?= $_SESSION['dir'] ?>', 'HoverBig')" 
                                   onclick="clickSound('<?= $_SESSION['dir'] ?>', 'Sent', 'btini', 1005)" 
                                   class="<?= $trabajar ?> bgb btn btn-zelda">
                                    Empezar sesión
                                </a>
                                <?= Html::a('', ['sesiones/nuevo'], ['class' => 'd-none', 'id' => 'btini']) ?>

                                <a onmouseover="hoverSound('<?= $_SESSION['dir'] ?>', 'HoverBig')" 
                                   onclick="clickSound('<?= $_SESSION['dir'] ?>', 'Receive', 'btparar', 1005)" 
                                   class="<?= $parar ?> bgb btn btn-zelda"
                                   id="boton-parar">
                                    Finalizar sesión
                                </a>
                                <?= Html::a('', ['sesiones/editar', 'id' => $_SESSION['idSesion']], ['class' => 'd-none', 'id' => 'btparar']) ?>


                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </div>
</div>

views/tareas/_form.php
<?php

use yii\bootstrap4\Html;
use yii\bootstrap4\ActiveForm;
use yii\widgets\LinkPager;

/* @var $this yii\web\View */
/* @var $model app\models\Tareas */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="h-100 row">
    <div class="col align-self-lg-center">
        <div class="row justify-content-center">

            <?php
            $config = ['template' => "{input}\n{error}\n{hint}"];
            $form = ActiveForm::begin();
            ?>

            <div class="my-4 font-weight-bolder vista-mod-ancho"
                 onclick="hoverSound('<?= $_SESSION['dir'] ?>', 'HoverSmall')"
                 onkeypress="hoverSound('<?= $_SESSION['dir'] ?>', 'HoverSmall')"
                 >
                     <?= $form->field($model, 'nombre')->textInput(['maxlength' => true]) ?>
            </div>

            <div class="pb-5 font-weight-bolder field table table-striped"
                 onclick="hoverSound('<?= $_SESSION['dir'] ?>', 'HoverSmall')"
                 onkeypress="hoverSound('<?= $_SESSION['dir'] ?>', 'HoverSmall')"
                 >
                     <?= $form->field($model, 'descripcion')->textarea(['rows' => '6', 'maxlength' => true, 'placeholder' => 'Descripción de la tarea...', 'class' => 'form-control text-justify', 'id' => 'texto-campo'])->label('Descripcion de la tarea') ?>
            </div>
            <div class="pt-4 pb-5"></div>

            <?= $form->field($model, 'completada')->textInput(['class' => 'd-none'])->label(false) ?>
            <?= $form->field($model, 'id_objetivo')->textInput(['class' => 'd-none'])->label(false) ?>

            <div class="form-group">

                <!--< ?= Html::submitButton('Guardar', ['class' => 'bgb btn btn-zelda my-5 w-50', 'name' => 'siguiente-button', 'id' => 'submit-button']) ?>-->
                <a onmouseover="hoverSound('<?= $_SESSION['dir'] ?>', 'HoverBig')" 
                   onclick="clickSound('<?= $_SESSION['dir'] ?>', 'Mod_Close', 'sbtn', 663)" 
                   class="bgb btn btn-zelda my-5 w-50"
                   id="submit-button">
                    Guardar
                </a>
                <?= Html::submitButton('', ['class' => 'd-none', 'name' => 'siguiente-button', 'id' => 'sbtn']) ?>
            </div>

            <?php ActiveForm::end(); ?>

        </div>
    </div>
</div>

views/tareas/continuar.php
<?php

use yii\bootstrap4\Html;
use yii\widgets\ListView;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
$this->title = 'Continuar';
?>

<!--BOTONES HOME, BACK, EDITAR-->
<div class="col align-self-lg-center">
    <div class="row justify-content-center">
        <div class="col-md-1 col-sm-1 mt-7 ml-5 fixed-top"> 
            <div class="col-md-1 col-sm-3">
                <a onmouseover="hoverSound('<?= $_SESSION['dir'] ?>', 'HoverSmall')" 
                   onclick="clickSound('<?= $_SESSION['dir'] ?>', 'Back', 'bbtn', 419)" 
                   class="a fas fa-angle-left display-3 mt-5 text-white text-center">
                </a>
                <?= Html::a('', ['objetivos/continuar', 'id' => $_SESSION['idObjetivo'], 'hito' => $_SESSION['idHito']], ['class' => 'd-none', 'id' => 'bbtn']) ?>
            </div> 
        </div> 

        <div class="col-md-1 col-sm-1 mt-7 ml-6 fixed-top"> 
            <div class="col-md-1 col-sm-3">
                <a onmouseover="hoverSound('<?= $_SESSION['dir'] ?>', 'HoverSmall')" 
                   onclick="clickSound('<?= $_SESSION['dir'] ?>', 'Mod_Open', 'ebtn', 974)" 
                   class="a fa-solid fa-paintbrush display-3 mt-5 text-white text-center">
                </a>
                <?= Html::a('', ['tareas/editar', 'id' => $_SESSION['idTarea']], ['class' => 'd-none', 'id' => 'ebtn']) ?>
            </div> 
        </div> 
    </div>
</div>



<div class="h-100 row example-1 square scrollbar-dusty-grass square thin bordered-z">
    <div class="col align-self-lg-center">
        <div class="row justify-content-center">

            <div class="col-md-2 col-sm-2">
            </div>

            <div class="col-md-8 col-sm-8">

                <div class="my-5 pb-5">

                    <div class="pb-5">
                        <div class="pb-5">
                            <?=
                            ListView::widget([
                                "pager" => [
                                    "class" => \yii\bootstrap4\LinkPager::class
                                ],
                                "dataProvider" => $dp,
                                "itemView" => "_continuar",
                                "layout" => "{items}",
                                "viewParams" => ['ls' => $ls],
                            ])
                            ?>

                        </div>
                    </div>

                </div>

            </div>

            <div class="col-md-2 col-sm-2">
            </div>

        </div>
    </div>
</div>

views/tareas/create.php
<?php

use yii\bootstrap4\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Tareas */

$this->title = 'Create Tareas';
$this->params['breadcrumbs'][] = ['label' => 'Tareas', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="tareas-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>