models/Objetivos.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "objetivos".
 *
 * @property int $id
 * @property string $titulo
 * @property string|null $descripcion
 *
 * @property Hitos[] $hitos
 * @property ObjetivosEnHitos[] $objetivosEnHitos
 * @property ProductosAObtener[] $productosAObteners
 * @property Tareas[] $tareas
 */
class Objetivos extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'objetivos';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['titulo'], 'required'],
            [['titulo'], 'string', 'max' => 20],
            [['descripcion'], 'string', 'max' => 300],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'titulo' => 'Titulo',
            'descripcion' => 'Descripcion',
        ];
    }

    /**
     * Gets query for [[Hitos]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getHitos()
    {
        return $this->hasMany(Hitos::className(), ['id' => 'id_hito'])->viaTable('objetivos_en_hitos', ['id_objetivo' => 'id']);
    }

    /**
     * Gets query for [[ObjetivosEnHitos]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getObjetivosEnHitos()
    {
        return $this->hasMany(ObjetivosEnHitos::className(), ['id_objetivo' => 'id']);
    }

    /**
     * Gets query for [[ProductosAObteners]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getProductosAObteners()
    {
        return $this->hasMany(ProductosAObtener::className(), ['id_objetivo' => 'id']);
    }

    /**
     * Gets query for [[Tareas]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getTareas()
    {
        return $this->hasMany(Tareas::className(), ['id_objetivo' => 'id']);
    }
}

controllers/ObjetivosController.php
<?php

namespace app\controllers;

use app\models\Objetivos;
use app\models\Tareas;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;

/**
 * ObjetivosController implements the CRUD actions for Objetivos model.
 */
class ObjetivosController extends Controller {

    public function actionNuevo() {
        $_SESSION['layout'] = false;
//        if ($_SESSION['vista'] == 'Main' || $_SESSION['vista'] == 'Nuevo' || $_SESSION['vista'] == 'Continuar') {

            $model = new Objetivos();

            if ($this->request->isPost) {

                if ($model->load($this->request->post()) && $model->save()) {
                    $_SESSION['idObjetivo'] = $model->id;
                    return $this->redirect(['productos-a-obtener/nuevo']);
                }
//                }
            } else {
                $model->loadDefaultValues();
            }

            return $this->render('nuevo', [
                        'model' => $model,
            ]);
//        }
//        return $this->redirect(["site/index"]);
    }

    public function actionContinuar($id) {
        ProyectosController::updateLayout($_SESSION['idProyecto'],'update');
        $model = $this->findModel($id);
        $_SESSION['layout'] = true;
        $_SESSION['continuar'] = true;
        $productos = ArrayHelper::getColumn($model->productosAObteners, 'resultado');
        $_SESSION['idObjetivo'] = $id;

        $dataProvider = new ActiveDataProvider([
            'query' => Tareas::find()->where("id_objetivo =" . $id)
        ]);

        return $this->render('continuar', [
                    'dp' => $dataProvider,
                    'titulo' => $model->titulo,
                    'productos' => $productos,
        ]);
    }

    public function actionEditar($id) {
        $model = $this->findModel($id);
        $_SESSION['layout'] = true;
        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['objetivos/continuar', 'id' => $_SESSION['idObjetivo'], 'hito' => $_SESSION['idHito']]);
        }

        return $this->render('editar', [
                    'model' => $model,
        ]);
    }

    /**
     * @inheritDoc
     */
    public function behaviors() {
        return array_merge(
                parent::behaviors(),
                [
                    'verbs' => [
                        'class' => VerbFilter::className(),
                        'actions' => [
                            'delete' => ['POST'],
                        ],
                    ],
                ]
        );
    }

    /**
     * Lists all Objetivos models.
     *
     * @return string
     */
    public function actionIndex() {
        $dataProvider = new ActiveDataProvider([
            'query' => Objetivos::find(),
                /*
                  'pagination' => [
                  'pageSize' => 50
                  ],
                  'sort' => [
                  'defaultOrder' => [
                  'id' => SORT_DESC,
                  ]
                  ],
                 */
        ]);

        return $this->render('index', [
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Objetivos model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id) {
        return $this->render('view', [
                    'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Objetivos model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate() {
        $model = new Objetivos();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
                    'model' => $model,
        ]);
    }

    /**
     * Updates an existing Objetivos model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id) {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
                    'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Objetivos model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id) {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Objetivos model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Objetivos the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Objetivos::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\Logros;
use app\models\ContactForm;
use app\models\ValidarFormulario;
use app\models\ValidarFormularioAjax;
use yii\widgets\ActiveForm;
use app\models\FormRegister;
use app\models\Users;
use yii\web\Session;
use app\models\FormRecoverPass;
use app\models\FormResetPass;
use yii\helpers\Url;
use yii\helpers\Html;
use app\controllers\ProyectosController;

// ejemplo de pruebas del proyecto: "C:\xampp\htdocs\dam\proyectos\gestionproyectos"
// direccion de la carpeta del proyecto posterior al htdocs: --> 'dam\proyectos\gestionproyectos' <--
//substr(Yii::$app->homeUrl, 1,-14) = substr(Yii::$app->homeUrl, 1,-14); //obtener automaticamente la direccion
$homeUrl = Yii::$app->homeUrl;
$_SESSION['dir'] = substr($homeUrl, 1, -14);

if (!isset($_SESSION['proyecto'])) {
    $_SESSION['proyecto'] = "null";
}
if (!isset($_SESSION['plazo'])) {
    $_SESSION['plazo'] = "null";
}
if (!isset($_SESSION['tiempo'])) {
    $_SESSION['tiempo'] = "null";
}
if (!isset($_SESSION['totalHitos'])) {
    $_SESSION['totalHitos'] = "null";
}
if (!isset($_SESSION['totalObjetivos'])) {
    $_SESSION['totalObjetivos'] = "null";
}
if (!isset($_SESSION['totalTareas'])) {
    $_SESSION['totalTareas'] = "null";
}
if (!isset($_SESSION['tipo'])) {
    $_SESSION['tipo'] = "null";
}
if (!isset($_SESSION['idObjetivo'])) {
    $_SESSION['idObjetivo'] = "null";
}
if (!isset($_SESSION['idHito'])) {
    $_SESSION['idHito'] = "null";
}
if (!isset($_SESSION['pagProyecto'])) {
    $_SESSION['pagProyecto'] = 0;
}

class SiteController extends Controller {

    /**
     * {@inheritdoc}
     */
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex() {

//        $_SESSION['dir'] = substr(Yii::$app->homeUrl, 1, -14); //obtener automaticamente la direccion

        $_SESSION['continuar'] = false;
        $_SESSION['layout'] = false;
        $_SESSION['idProyecto'] = null;
        return $this->render('index');
    }

    public function actionComenzar() {
//        if ($_SESSION['vista'] == 'Main' || $_SESSION['vista'] == 'Comenzar') { //con el 'or' no devolvemos al usuario al main al recargar la pagina
        return $this->redirect(['proyectos/nuevo']);
//        }
//        return $this->render('index');
    }

    public function actionContinuar() {
//            if ($_SESSION['vista'] == 'Main' || $_SESSION['vista'] == 'Nuevo') {
        if (isset($_SESSION['idProyecto'])) {
            return $this->redirect(['proyectos/continuar', 'id' => $_SESSION['idProyecto'], /* 'hitos'=> "null", */ 'hito' => $_SESSION['idHito']]);
        } else {
        return $this->redirect(['proyectos/seleccionar']);
        }
//    }
//        return $this->render('index');
    }

    public function actionLogros() {
        $model = UsersController::findThis(Yii::$app->user->getId());

        $proyectos = $model->proyectos;

        $horas = 0;
        $minutos = 0;
        $segundos = 0;
        $totalHitos = 0;
        $hitosCompletados = 0;
        $objetivosCompletados = 0;
        $totalObjetivos = 0;
        $tareasCompletadas = 0;
        $totalTareas = 0;

        foreach ($proyectos as $proyecto) {
            $horas += ProyectosController::updateLayout($proyecto->id, 'horas');
            $minutos += ProyectosController::updateLayout($proyecto->id, 'minutos');
            $segundos += ProyectosController::updateLayout($proyecto->id, 'segundos');
            $hitosCompletados += ProyectosController::updateLayout($proyecto->id, 'hitosCompletados');
            $totalHitos += ProyectosController::updateLayout($proyecto->id, 'totalHitos');
            $objetivosCompletados += ProyectosController::updateLayout($proyecto->id, 'objetivosCompletados');
            $totalObjetivos += ProyectosController::updateLayout($proyecto->id, 'totalObjetivos');
            $tareasCompletadas += ProyectosController::updateLayout($proyecto->id, 'tareasCompletadas');
            $totalTareas += ProyectosController::updateLayout($proyecto->id, 'totalTareas');
        }

        $minutos += (int) ($segundos / 60);

        $horas += (int) ($minutos / 60);
        if ($horas < 10) {
            $horas = '0' . $horas;
        }

        $minutos -= 60 * (int) ($minutos / 60);
        if ($minutos < 10) {
            $minutos = '0' . $minutos;
        }

        $segundos -= 60 * (int) ($segundos / 60);
        if ($segundos < 10) {
            $segundos = '0' . $segundos;
        }

        $tiempo = 'Total: ' . $horas . ':' . $minutos/* . ' segundos: '.$segundos */;

        return $this->render('logros', [
                    'horas' => $horas,
                    'minutos' => $minutos,
                    'segundos' => $segundos,
                    'tiempo' => $tiempo,
                    'tiempo' => $tiempo,
                    'totalHitos' => $totalHitos,
                    'hitosCompletados' => $hitosCompletados,
                    'objetivosCompletados' => $objetivosCompletados,
                    'totalObjetivos' => $totalObjetivos,
                    'tareasCompletadas' => $tareasCompletadas,
                    'totalTareas' => $totalTareas,
                    'nProyectos' => count($proyectos),
        ]);
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin() {
//        if (!isset($_SESSION['presentacion'])) {
//            $_SESSION['presentacion'] = '';
//            $_SESSION['iniciar'] = 'd-none';
//        } else {
        $_SESSION['presentacion'] = 'd-none';
        $_SESSION['iniciar'] = '';
//        }
        $_SESSION['layout'] = 0;
        $_SESSION['dir'] = substr(Yii::$app->homeUrl, 1, -14); //obtener automaticamente la direccion

        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->contraseña = '';
        return $this->render('login', [
                    'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout() {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionSalir() {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact() {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
                    'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionCrud() {
        $_SESSION['presentacion'] = 'd-none';
        $_SESSION['iniciar'] = '';
        return $this->redirect(['site/login']);
    }

    // tut 1




    public function actionFormulario($mensaje = null) {
        return $this->render("formulario", ["mensaje" => $mensaje]);
    }

    public function actionRequest() {
        $mensaje = null;
        if (isset($_REQUEST["nombre"])) {
            $mensaje = "Bien, has enviando tu nombre correctamente: " . $_REQUEST["nombre"];
        }
        $this->redirect(["site/formulario", "mensaje" => $mensaje]);
    }

    public function actionValidarformulario() {

        $model = new ValidarFormulario;
        $msg = null;

        if ($model->load(Yii::$app->request->post())) {
            if ($model->validate()) {
                //Por ejemplo, consultar en una base de datos
                $msg = "funciona";
                $model->nombre = null;
                $model->email = null;
            } else {
                $model->getErrors();
            }
        }

        return $this->render("validarformulario", ["model" => $model, 'msg' => $msg]);
    }

    public function actionValidarformularioajax() {
        $model = new ValidarFormularioAjax;
        $msg = null;

        if ($model->load(Yii::$app->request->post()) && Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }

        if ($model->load(Yii::$app->request->post())) {
            if ($model->validate()) {
                //Por ejemplo hacer una consulta a una base de datos
                $msg = "Enhorabuena formulario enviado correctamente";
                $model->nombre = null;
                $model->email = null;
            } else {
                $model->getErrors();
            }
        }

views/objetivos/continuar.php
<?php

use yii\bootstrap4\Html;
use yii\widgets\ListView;

$this->title = 'Continuar';
?>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        empty();
    });
</script>


<!--BOTONES HOME, BACK, EDITAR-->
<div class="col align-self-lg-center">
    <div class="row justify-content-center">
        <div class="col-md-1 col-sm-1 mt-7 ml-5 fixed-top"> 
            <div class="col-md-1 col-sm-3">
                <a onmouseover="hoverSound('<?= $_SESSION['dir'] ?>', 'HoverSmall')" 
                   onclick="clickSound('<?= $_SESSION['dir'] ?>', 'Back', 'bbtn', 419)" 
                   class="a fas fa-angle-left display-3 mt-5 text-white text-center">
                </a>
                <?= Html::a('', ['proyectos/continuar', 'id' => $_SESSION['idProyecto'], 'hito' => $_SESSION['idHito']], ['class' => 'd-none', 'id' => 'bbtn']) ?>
            </div> 
        </div> 

        <div class="col-md-1 col-sm-1 mt-7 ml-6 fixed-top"> 
            <div class="col-md-1 col-sm-3">
                <a onmouseover="hoverSound('<?= $_SESSION['dir'] ?>', 'HoverSmall')" 
                   onclick="clickSound('<?= $_SESSION['dir'] ?>', 'Mod_Open', 'ebtn', 974)" 
                   class="a fa-solid fa-paintbrush display-3 mt-5 text-white text-center">
                </a>
                <?= Html::a('', ['objetivos/editar', 'id' => $_SESSION['idObjetivo']], ['class' => 'd-none', 'id' => 'ebtn']) ?>
            </div> 
        </div> 
    </div>
</div>


<!--ESTE ES EL BUENO AHORA-->
<!--<div class=" col-md-2 col-sm-2 mt-7 ml-5 fixed-top">
    <div class="col-md-1 col-sm-3">

< ?= Html::a('', ['proyectos/continuar', 'id' => $_SESSION['idProyecto'], 'hito' => $_SESSION['idHito']], ['class' => 'a fas fa-angle-left display-3 mt-5 text-white text-center']) ?>
    </div> 
</div> -->

<div class="h-100 row example-1 square scrollbar-dusty-grass square thin bordered-z">
    <div class="col align-self-lg-center">
        <div class="row justify-content-center">

            <div class="col-md-3 col-sm-3">
            </div>

            <div class="col-md-6 col-sm-6">

                <div class="my-5 pb-5">
                    <h1 class="shine text-white display-4 text-center">Objetivo: <?= ucfirst($titulo) ?></h1>

                    <!--RESULTADOS ESPERADOS-->
                    <div class="mt-5 bar">
                        <p class="bar">Productos esperados para este objetivo</p>

                        <?php
                        $i = 0;
                        foreach ($productos as $producto) {
                            $i++;
                            echo '<p><i class="fa-solid fa-caret-right"></i> ' . $producto . '</p>';
                        }
                        ?>
                    </div>

                    <!--TAREAS-->
                    <div class="pb-5">
                        <div class="pb-5">
                            <?=
                            ListView::widget([
                                "pager" => [
                                    "class" => \yii\bootstrap4\LinkPager::class
                                ],
                                "dataProvider" => $dp,
                                "itemView" => "_continuar",
                                "layout" =>
                                "{items}\n " .
//                                aqui podria controlar si hay 20 paneles no mostrar este elemento, poniendo un tag a los paneles y contandolos.
                                Html::a(''
                                        . ' <div class="bgb text-center" '
                                        . 'onmouseenter="hoverSound(\'' . $_SESSION['dir'] . '\', \'Extra_Click\')">'
                                        . '     <div class="borde btn-zelda">'
                                        . '         <i class="fas fa-plus"></i>'
                                        . '         <p class="display-5 mb-n1">Nueva tarea</p>'
                                        . '     </div>'
                                        . ' </div>'
                                        . '', ['tareas/nuevo'], ['class' => 'a text-white text-center '])
                                . " \n{summary}\n{pager}",
                            ])
                            ?>

                        </div>
                    </div>

                </div>

            </div>

            <div class="col-md-3 col-sm-3">
            </div>
            <div id="vacio" class="d-none">
                <?=
                Html::a(''
                        . ' <div class="bgb text-center" '
                        . 'onmouseenter="hoverSound(\'' . $_SESSION['dir'] . '\', \'Extra_Click\')">'
                        . '     <div class="borde btn-zelda">'
                        . '         <i class="fas fa-plus"></i>'
                        . '         <p class="display-5 mb-n1">Nueva tarea</p>'
                        . '     </div>'
                        . ' </div>'
                        . '', ['tareas/nuevo'], ['class' => 'a text-white text-center '])
                ?>
            </div>
        </div>
    </div>
</div>

views/objetivos/nuevo.php
<?php

use yii\bootstrap4\Html;
use kartik\form\ActiveForm;
use kartik\date\DatePicker;

$this->title = 'Nuevo';
?>


<script>
    document.addEventListener("DOMContentLoaded", function () {
        vista('<?= $_SESSION['vista'] ?>');
    });
</script>

<div class="h-100 row text-center">
    <div class="col align-self-lg-center">
        <div class="row justify-content-center">

            <div class="col-md-3 col-sm-3">
                <!--<p>el id seria: < ?= $id ?></p>-->
                <!--<p>la var submit es: < ?= $_SESSION['submit'] ?></p>-->
                <!--<p>la var id es: < ?= $_SESSION['idProyecto'] ?></p>-->
            </div>

            <!--titulo-->
            <div id="form" class="col-md-6 col-sm-6 text-center">
                <?php
                $config = ['template' => "{input}\n{error}\n{hint}"];
                $form = ActiveForm::begin();
                ?>

                <div id="nuevo" class="op80 bgb text-center">
                    <div class="borde p-5">
                        <div class="">
                            <p class="shine text-white display-4">¿Quieres añadir un objetivo ahora?</p>
                        </div>

                        <div class="mt-5 row justify-content-center">

                            <div class="my-5 bgb col-md-4 col-sm-4 text-center">
                                <a id="continuar" 
                                   class="btn btn-zelda" 
                                   onmouseover="hoverSound('<?= $_SESSION['dir'] ?>', 'HoverBig')"
                                   onclick="mostrar('nuevo', 'nombre'), clickSound('<?= $_SESSION['dir'] ?>', 'Talk_Next', 'null', 0)">Si</a>
                            </div>

                            <div class="col-md-1 col-sm-1">
                            </div>

                            <div class="my-5 bgb col-md-4 col-sm-4 text-center">
                                <!--<a class="btn btn-zelda" onclick="generico('nuevo', 'submit', 'nombre', 'Objetivo')">Aún no</a>-->
                                <a onmouseover="hoverSound('<?= $_SESSION['dir'] ?>', 'HoverBig')" 
                                   onclick="clickSound('<?= $_SESSION['dir'] ?>', 'Talk_No', 'noAñadir', 663)" 
                                   class="btn btn-zelda">
                                    Aún no
                                </a>
                                <?= Html::a('', ['site/continuar'], ['id' => 'noAñadir']) ?>
                            </div>

                        </div>
                    </div>
                </div>

                <div id="nombre" class="d-none text-center">
                    <div class="borde p-5">
                        <div class="col align-self-lg-center">

                            <p class="shine text-white display-4">Escribe el título del objetivo...</p>
                            <div class="row justify-content-center">
                                <div class="w-50 field my-3"
                                     onclick="hoverSound('<?= $_SESSION['dir'] ?>', 'HoverSmall')"
                                     onkeypress="hoverSound('<?= $_SESSION['dir'] ?>', 'HoverSmall')"
                                     >
                                         <?= $form->field($model, 'titulo')->textInput(['maxlength' => true, 'placeholder' => 'Título del objetivo...', 'id' => 'nombre-campo'])->label(false) ?>
                                </div>
                            </div>
                            <div class="row justify-content-center">
                                <div class="w-25 my-5 bgb">
                                    <a class="btn btn-zelda" 
                                       onmouseover="hoverSound('<?= $_SESSION['dir'] ?>', 'HoverBig')"
                                       onclick="siguiente('nombre', 'descripcion'), clickSound('<?= $_SESSION['dir'] ?>', 'Talk_Next', 'null', 0)">Siguiente</a>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>

                <!--plazo-->
                <div id="descripcion" class="d-none text-center">
                    <div class="borde p-5">
                        <div class="">
                            <p class="shine text-white display-4">¿Quieres añadirle una descripción a este objetivo ahora?</p>
                        </div>

                        <div class="mt-5 row justify-content-center">

                            <div class="my-5 bgb col-md-4 col-sm-4 text-center">
                                <a class="btn btn-zelda" 
                                   onmouseover="hoverSound('<?= $_SESSION['dir'] ?>', 'HoverBig')"
                                   onclick="mostrar('descripcion', 'texto'), clickSound('<?= $_SESSION['dir'] ?>', 'Talk_Next', 'null', 0)">Si</a>
                            </div>

                            <div class="col-md-1 col-sm-1">
                            </div>

                            <div class="my-5 bgb col-md-4 col-sm-4 text-center">
                                <a class="btn btn-zelda" 
                                   onmouseover="hoverSound('<?= $_SESSION['dir'] ?>', 'HoverBig')"
                                   onclick="generico('descripcion', 'submit', 'texto', 'Descripción'), clickSound('<?= $_SESSION['dir'] ?>', 'Talk_No', 'null', 0)">No</a>
                            </div>

                        </div>
                    </div>
                </div>

                <div id="texto" class="d-none text-center">
                    <div class="borde p-5">
                        <div class="col align-self-lg-center">

                            <p class="shine text-white display-4">Escribe una descripción del objetivo...</p>
                            <div class="row justify-content-center">
                                <div class="w-75 field my-3"
                                    onclick="hoverSound('<?= $_SESSION['dir'] ?>', 'HoverSmall')"
                                    onkeypress="hoverSound('<?= $_SESSION['dir'] ?>', 'HoverSmall')"
                                    >
                                    <?= $form->field($model, 'descripcion')->textarea(['rows' => '6', 'maxlength' => true, 'placeholder' => 'Descripción del objetivo...', 'class' => 'dd-none', 'id' => 'texto-campo'])->label(false) ?>
                                </div>
                            </div>
                            <div class="row justify-content-center pt-5">
                                <div class="w-25 my-5 bgb">
                                    <a class="btn btn-zelda" 
                                       onmouseover="hoverSound('<?= $_SESSION['dir'] ?>', 'HoverBig')"
                                       onclick="siguiente('texto', 'submit'), clickSound('<?= $_SESSION['dir'] ?>', 'Talk_End', 'null', 0)">Siguiente</a>
                                </div>
                            </div>

                        </div>
                    </div>

                </div>
                <!--submit-->            
                <div  onmouseover="submit()" id="submit" class="d-none text-center">
                    <!--finalizar el formulario-->
                    <?= Html::submitButton('Siguiente', ['class' => 'd-none btn btn-zelda', 'name' => 'siguiente-button', 'id' => 'submit-button']) ?>

                </div>
                <?php ActiveForm::end(); ?>
            </div>
            <div class="col-md-3 col-sm-3">

            </div>

        </div>
    </div>
</div>